require 'pry'
require 'nokogiri'
require 'open-uri'
require 'tty-link'
require 'colorize'

require_relative '../lib/best_things_to_do_in_melbourne/cli'
require_relative '../lib/best_things_to_do_in_melbourne/scraper'
require_relative '../lib/best_things_to_do_in_melbourne/todo'
require_relative '../lib/best_things_to_do_in_melbourne/logo'